"""empty message

Revision ID: 358c1ab8dec1
Revises: b06c47213cc0
Create Date: 2025-04-25 18:29:06.521995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '358c1ab8dec1'
down_revision = 'b06c47213cc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Comment', schema=None) as batch_op:
        batch_op.drop_constraint('Comment_comment_text_key', type_='unique')

    with op.batch_alter_table('Media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('IMAGE', 'VIDEO', name='mediatype'), nullable=False))

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('User_firtsname_key', type_='unique')
        batch_op.drop_constraint('User_lastname_key', type_='unique')
        batch_op.drop_column('firtsname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firtsname', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('User_lastname_key', ['lastname'])
        batch_op.create_unique_constraint('User_firtsname_key', ['firtsname'])
        batch_op.drop_column('firstname')

    with op.batch_alter_table('Media', schema=None) as batch_op:
        batch_op.drop_column('type')

    with op.batch_alter_table('Comment', schema=None) as batch_op:
        batch_op.create_unique_constraint('Comment_comment_text_key', ['comment_text'])

    # ### end Alembic commands ###
