"""empty message

Revision ID: a610ca0c4b11
Revises: e8ece3632c4b
Create Date: 2025-04-25 18:09:02.977176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a610ca0c4b11'
down_revision = 'e8ece3632c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Follower', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'User', ['user_from_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Follower', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
